# Generated by Django 4.1.3 on 2022-11-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusmodel',
            options={'verbose_name': 'О компаниии', 'verbose_name_plural': 'О компаниии'},
        ),
        migrations.AlterModelOptions(
            name='aboutusmodeltranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'О компаниии Translation'},
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Активирован'),
        ),
    ]
