# Generated by Django 4.1.3 on 2022-11-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productmodeltranslation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='priority',
            field=models.IntegerField(default=50, verbose_name='Приоритет выдачи'),
        ),
    ]
