# Generated by Django 4.1.3 on 2022-11-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_categorymodel_categorymodeltranslation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='categorymodel',
            managers=[
            ],
        ),
    ]
