# Generated by Django 4.1.3 on 2022-11-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_categorymodel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodeltranslation',
            name='slug',
            field=models.SlugField(default='', max_length=300),
        ),
    ]
