# Generated by Django 4.1.3 on 2022-11-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_categorymodeltranslation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodeltranslation',
            name='slug',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(default='', max_length=300),
        ),
    ]
