# Generated by Django 4.1.3 on 2022-11-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='priority',
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(default='', max_length=300, verbose_name='Путь'),
        ),
    ]
