# Generated by Django 4.1.3 on 2022-11-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_categorymodel_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='catalog.categorymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='catalog.categorymodel'),
        ),
    ]
