# Generated by Django 4.1.3 on 2022-11-23 09:46

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_servicemodel_category_alter_productmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdvantagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styles', models.CharField(max_length=500, verbose_name='Стили')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='catalog.productmodel')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductAdvantagesModelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.CharField(max_length=5000, verbose_name='Текст')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.productadvantagesmodel')),
            ],
            options={
                'verbose_name': 'Преимущество Translation',
                'db_table': 'catalog_productadvantagesmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
