# Generated by Django 4.1.3 on 2022-11-23 10:14

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_productadvantagesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPropertiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styles', models.CharField(help_text='Стили TailwindCSS, которые будут добавлены к классу (https://tailwindcss.com)', max_length=500, verbose_name='Стили')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_product', to='catalog.productmodel')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='productadvantagesmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages_product', to='catalog.productmodel'),
        ),
        migrations.AlterField(
            model_name='productadvantagesmodel',
            name='styles',
            field=models.CharField(help_text='Стили TailwindCSS, которые будут добавлены к классу (https://tailwindcss.com)', max_length=500, verbose_name='Стили'),
        ),
        migrations.AlterField(
            model_name='productadvantagesmodeltranslation',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Текст'),
        ),
        migrations.CreateModel(
            name='ProductPropertiesModelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст')),
                ('value', models.CharField(max_length=1000, verbose_name='Значение')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.productpropertiesmodel')),
            ],
            options={
                'verbose_name': 'Свойство Translation',
                'db_table': 'catalog_productpropertiesmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
